version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv run --group docs --no-group dev --locked --no-cache mkdocs build -d $READTHEDOCS_OUTPUT/html
