version: 2
build:
  os: ubuntu-lts-latest
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv run --group docs --no-group dev --locked --no-cache --python 3.13 mkdocs build -d $READTHEDOCS_OUTPUT/html
