site_name: aiopygismeteo
repo_url: https://github.com/monosans/aiopygismeteo
repo_name: monosans/aiopygismeteo
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.top
    - toc.follow
  icon:
    logo: fontawesome/solid/droplet
    repo: fontawesome/brands/github
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Тёмный режим
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Светлый режим
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/monosans
      name: Telegram разработчика
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/monosans
      name: LinkedIn разработчика
markdown_extensions:
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - minify_html
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.aiohttp.org/en/stable/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://typing-extensions.readthedocs.io/en/stable/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            filters:
              - "!^_(?:[^_].*[^_]|_(?:all|doc|format|main|module|new|slots|str)__)$"
            heading_level: 3
            members_order: source
            merge_init_into_class: true
            preload_modules:
              - pygismeteo_base
            separate_signature: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false
            show_submodules: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
