site_name: aiopygismeteo

repo_name: monosans/aiopygismeteo
repo_url: https://github.com/monosans/aiopygismeteo
edit_uri: edit/main/docs/

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Светлый режим
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Тёмный режим
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/droplet
  font: false

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/monosans
      name: Developer's Telegram
    - icon: fontawesome/brands/vk
      link: https://vk.com/id607137534
      name: Developer's VK

markdown_extensions:
  - pymdownx.superfences

nav:
  - index.md
  - installation.md
  - ide.md
  - gismeteo.md
  - current.md
  - step3.md
  - step6.md
  - step24.md
  - search.md
  - session.md
  - types.md
