site_name: aiopygismeteo
repo_url: https://github.com/monosans/aiopygismeteo
repo_name: monosans/aiopygismeteo
edit_uri: edit/main/docs/
nav:
  - index.md
  - installation.md
  - gismeteo.md
  - current.md
  - step3.md
  - step6.md
  - step24.md
  - search.md
  - session.md
  - types.md
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - toc.follow
  font: false
  icon:
    logo: fontawesome/solid/droplet
    repo: fontawesome/brands/github
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Тёмный режим
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Светлый режим
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/monosans
      name: Telegram разработчика
    - icon: fontawesome/brands/vk
      link: https://vk.com/id607137534
      name: VK разработчика
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/monosans
      name: LinkedIn разработчика
markdown_extensions:
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - minify_html
