site_name: aiopygismeteo
site_description: Asynchronous wrapper for Gismeteo.ru API
site_author: monosans
repo_name: monosans/aiopygismeteo
repo_url: https://github.com/monosans/aiopygismeteo
edit_uri: edit/main/docs/
theme:
  name: material
  language: ru
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: fontawesome/solid/sun
        name: Светлый режим
    - scheme: default
      primary: black
      toggle:
        icon: fontawesome/solid/moon
        name: Тёмный режим
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/tint
  font: false
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/monosans
      name: Developer's Telegram
    - icon: fontawesome/brands/vk
      link: https://vk.com/id607137534
      name: Developer's VK
nav:
  - Домашняя страница: index.md
  - Установка: installation.md
  - Подходящие IDE: ide.md
  - Класс Gismeteo: gismeteo.md
  - Методы класса Gismeteo:
      - current (текущая погода): current.md
      - step3 (с шагом 3 часа): step3.md
      - step6 (с шагом 6 часов): step6.md
      - step24 (с шагом 24 часа): step24.md
      - get_id_by_query: get_id_by_query.md
  - Исключения (exceptions): exceptions.md
  - Типизация: typing.md
  - Свой экземпляр aiohttp.ClientSession: session.md
markdown_extensions:
  - pymdownx.superfences
