name: CI
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  check:
    if: ${{ always() && github.event_name == 'pull_request' }}
    needs:
      - docs-build
      - pre-commit
      - pytest
    runs-on: ubuntu-24.04
    steps:
      - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
  docs-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.14"
          enable-cache: true
      - run: uv run --group docs --no-group dev --locked zensical build
      - if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: site
  docs-deploy:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    needs: docs-build
    runs-on: ubuntu-24.04
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.14"
          enable-cache: false
      - run: uvx --no-cache prek run --all-files --show-diff-on-failure
        env:
          RUFF_OUTPUT_FORMAT: github
  pytest:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.15"
      fail-fast: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - run: uv run --locked pytest
