name: Publish
on:
  push:
    tags:
      - v*
jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'monosans' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build --no-cache
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
