name: Publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'monosans' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v4
      - run: uv build --python 3.13 --no-cache
      - uses: pypa/gh-action-pypi-publish@release/v1
