name: Publish
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  publish-pypi:
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'monosans' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
      - run: uv build --python 3.13 --no-cache
      - run: uv publish --trusted-publishing always --no-cache
