name: Publish
on:
  push:
    tags:
      - v*
jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx run poetry build --no-interaction
      - uses: pypa/gh-action-pypi-publish@release/v1
