name: Publish
on:
  push:
    tags:
      - v*
jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'monosans' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv tool run poetry build --no-interaction
      - uses: pypa/gh-action-pypi-publish@release/v1
